import { Employee } from "@/types/employee";

export const getEmployeeTableData = (): Employee[] => {
  return [
    {
      id: "1",
      no: 1,
      employeeId: "E001",
      name: "John Doe",
      position: "Manager",
      location: "New York",
      status: "Active",
      number: 1234567890,
      birthday: "1990-01-01",
      email: "john.doe@example.com",
    },
    {
      id: "2",
      no: 2,
      employeeId: "E002",
      name: "Jane Smith",
      position: "Developer",
      location: "San Francisco",
      status: "Inactive",
      number: 9876543210,
      birthday: "1992-02-02",
      email: "jane.smith@example.com",
    },

    {
      id: "3",
      no: 3,
      employeeId: "E003",
      name: "Alice Johnson",
      position: "Designer",
      location: "Los Angeles",
      status: "Active",
      number: 1122334455,
      birthday: "1991-03-03",
      email: "alice.johnson@example.com",
    },
    {
      id: "4",
      no: 4,
      employeeId: "E004",
      name: "Bob Brown",
      position: "Tester",
      location: "Chicago",
      status: "Active",
      number: 2233445566,
      birthday: "1989-04-04",
      email: "bob.brown@example.com",
    },
    {
      id: "5",
      no: 5,
      employeeId: "E005",
      name: "Charlie Davis",
      position: "Support",
      location: "Miami",
      status: "Inactive",
      number: 3344556677,
      birthday: "1993-05-05",
      email: "charlie.davis@example.com",
    },
    {
      id: "6",
      no: 6,
      employeeId: "E006",
      name: "Diana Evans",
      position: "HR",
      location: "Seattle",
      status: "Active",
      number: 4455667788,
      birthday: "1994-06-06",
      email: "diana.evans@example.com",
    },
    {
      id: "7",
      no: 7,
      employeeId: "E007",
      name: "Ethan Foster",
      position: "Analyst",
      location: "Boston",
      status: "Inactive",
      number: 5566778899,
      birthday: "1995-07-07",
      email: "ethan.foster@example.com",
    },
  ];
};
