import { ItineraryData } from "@/types/employee";

export const getEmployeeTableData = (): ItineraryData[] => {
  return [
    {
      id: 1,
      date: "2023-10-15",
      name: "ABC Cooperative",
      purpose: "Loan application",
      product: "Agricultural loan",
      remarks: "Approved",
      assign: "John Doe",
    },
    {
      id: 2,
      date: "2023-10-16",
      name: "XYZ Non-Cooperative",
      purpose: "Membership",
      product: "Savings account",
      remarks: "Pending",
      assign: "John Doe",
    },
    {
      id: 3,
      date: "2023-10-17",
      name: "DEF Cooperative",
      purpose: "Investment",
      product: "Time deposit",
      remarks: "Rejected",
      assign: "John Doe",
    },
    {
      id: 4,
      date: "2023-10-18",
      name: "GHI Non-Cooperative",
      purpose: "Consultation",
      product: "Financial advice",
      remarks: "Completed",
      assign: "John Doe",
    },
    {
      id: 5,
      date: "2023-10-19",
      name: "JKL Cooperative",
      purpose: "Loan payment",
      product: "Agricultural loan",
      remarks: "On time",
      assign: "John Doe",
    },
    {
      id: 6,
      date: "2023-10-20",
      name: "MNO Cooperative",
      purpose: "Loan application",
      product: "Business loan",
      remarks: "Processing",
      assign: "John Doe",
    },
    {
      id: 7,
      date: "2023-10-21",
      name: "PQR Cooperative",
      purpose: "Loan inquiry",
      product: "Personal loan",
      remarks: "Inquired",
      assign: "John Doe",
    },
    {
      id: 8,
      date: "2023-10-22",
      name: "STU Non-Cooperative",
      purpose: "Account opening",
      product: "Current account",
      remarks: "Approved",
      assign: "John Doe",
    },
    {
      id: 9,
      date: "2023-10-23",
      name: "VWX Cooperative",
      purpose: "Loan renewal",
      product: "Agricultural loan",
      remarks: "Renewed",
      assign: "John Doe",
    },
    {
      id: 10,
      date: "2023-10-24",
      name: "YZA Cooperative",
      purpose: "Training",
      product: "Financial literacy",
      remarks: "Completed",
      assign: "John Doe",
    },
    {
      id: 11,
      date: "2023-10-25",
      name: "BCD Non-Cooperative",
      purpose: "Consultation",
      product: "Investment advice",
      remarks: "Pending",
      assign: "John Doe",
    },
    {
      id: 12,
      date: "2023-10-26",
      name: "EFG Cooperative",
      purpose: "Loan application",
      product: "Housing loan",
      remarks: "Processing",
      assign: "John Doe",
    },
  ];
};
