import { Monitoring } from "@/types/monitoring";

export const getMonitoringTableData = (): Monitoring[] => {
  return [
    {
      id: "1",
      no: 1,
      employeeId: "E001",
      name: "John Doe",
      week1: "Done",
      week2: "Not started",
      week3: "Enable To start",
      week4: "No Task",
    },
    {
      id: "2",
      no: 2,
      employeeId: "E002",
      name: "Jane Smith",
      week1: "Done",
      week2: "Not started",
      week3: "Enable To start",
      week4: "No Task",
    },
    {
      id: "3",
      no: 3,
      employeeId: "E003",
      name: "Robert Johnson",
      week1: "In Progress",
      week2: "Done",
      week3: "Not started",
      week4: "No Task",
    },
    {
      id: "4",
      no: 4,
      employeeId: "E004",
      name: "Emily Davis",
      week1: "Done",
      week2: "Done",
      week3: "In Progress",
      week4: "Not started",
    },
    {
      id: "5",
      no: 5,
      employeeId: "E005",
      name: "Michael Wilson",
      week1: "Not started",
      week2: "Enable To start",
      week3: "No Task",
      week4: "No Task",
    },
    {
      id: "6",
      no: 6,
      employeeId: "E006",
      name: "Sarah Brown",
      week1: "Done",
      week2: "Done",
      week3: "Done",
      week4: "In Progress",
    },
    {
      id: "7",
      no: 7,
      employeeId: "E007",
      name: "David Miller",
      week1: "No Task",
      week2: "Not started",
      week3: "Enable To start",
      week4: "No Task",
    },
    {
      id: "8",
      no: 8,
      employeeId: "E008",
      name: "Jessica Taylor",
      week1: "Done",
      week2: "In Progress",
      week3: "Not started",
      week4: "Enable To start",
    },
    {
      id: "9",
      no: 9,
      employeeId: "E009",
      name: "Thomas Anderson",
      week1: "In Progress",
      week2: "Done",
      week3: "Done",
      week4: "Not started",
    },
    {
      id: "10",
      no: 10,
      employeeId: "E010",
      name: "Lisa Martinez",
      week1: "Done",
      week2: "No Task",
      week3: "No Task",
      week4: "No Task",
    },
    {
      id: "11",
      no: 11,
      employeeId: "E011",
      name: "Daniel Clark",
      week1: "Not started",
      week2: "Enable To start",
      week3: "No Task",
      week4: "No Task",
    },
  ];
};
